# Generated by Django 6.0.3 on 2026-05-07 17:04

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_proxygroup_savedsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='params',
            field=models.JSONField(validators=[users.models.validate_search_params]),
        ),
    ]
