# Generated by Django 6.0.3 on 2026-05-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_proxygroup_savedsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
