# Generated by Django 6.0.3 on 2026-05-06 15:25

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_savedsearch_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='params',
            field=models.JSONField(default=1, validators=[users.models.validate_search_params]),
            preserve_default=False,
        ),
    ]
