services:
  backend:
    container_name: cityscope-backend
    build: ./backend
    ports: 
      - 8000:8000
    env_file: backend/.env
    volumes:
      - ./backend:/app/backend
    depends_on:
      db:
        condition: service_healthy


  frontend:
    container_name: cityscope-frontend
    build: ./frontend
    ports:
      - 3000:3000
    env_file: frontend/.env.local
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules

  db:
    image: postgres:17
    container_name: cityscope-postgres
    env_file: backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  broker:
    container_name: redis
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  celery_beat:
    container_name: celery_beat
    env_file: backend/.env
    build: ./backend
    volumes:
      - ./backend:/app/backend
    command: celery -A cityscope beat -l INFO
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy

  celery_worker:
    container_name: celery_worker
    env_file: backend/.env
    build: ./backend
    volumes:
      - ./backend:/app/backend
    command: celery -A cityscope worker -l INFO
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy

volumes:
  pgdata: