# Generated by Django 6.0.3 on 2026-04-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='sourcerecord',
            options={'verbose_name': 'Source Record', 'verbose_name_plural': 'Source Records'},
        ),
        migrations.RenameField(
            model_name='sourcerecord',
            old_name='source_id',
            new_name='id'
        )
    ]
