# Generated by Django 6.0.3 on 2026-04-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_slug_alter_city_slug_alter_place_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('name', 'latitude', 'longitude'), name='unique_place'),
        ),
    ]
