# Generated by Django 6.0.3 on 2026-07-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_place_options_alter_place_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
    ]
